### ISSUE TITLE
how to know only locate price and not locate 

### ISSUE THREAD

**Issue by Stockxavier** [shner-elmo/TradeZero_API#5]
hello is there a way to know only the locates price and not locate

**Comment by shner-elmo** [comment]
Yes, there is a way.
To get the locate-price without accepting it, you must pass: `max_price=0`.

Because if the locate-price is less than `max_price` it will just decline the locate. 
Check out the docstring [here](https://github.com/shner-elmo/tradezero-api/blob/master/tradezero_api/main.py#L250), and you can see that [here](https://github.com/shner-elmo/tradezero-api/blob/master/tradezero_api/main.py#L308-L313) it will click on the cancel button instead of accept, and you can view the price from the named tuple that is returned by the function (try this: `print(tz.locate_stock('GME', 100, max_price=0).price_per_share`).

**Comment by Stockxavier** [comment]
thanks that will solve my problem ill test it out when market opens. also another question while i have the library connected to my tz account i cant open my tradezero right to watch charts etc?

**Comment by Stockxavier** [comment]
> Yes, there is a way. To get the locate-price without accepting it, you must pass: `max_price=0`.
> 
> Because if the locate-price is less than `max_price` it will just decline the locate. Check out the docstring [here](https://github.com/shner-elmo/tradezero-api/blob/master/tradezero_api/main.py#L250), and you can see that [here](https://github.com/shner-elmo/tradezero-api/blob/master/tradezero_api/main.py#L308-L313) it will click on the cancel button instead of accept, and you can view the price from the named tuple that is returned by the function (try this: `print(tz.locate_stock('GME', 100, max_price=0).price_per_share`).

this is the error i am getting ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 1
----> 1 print(tz.locate_stock('GME', 100, max_price=0).price_per_share)

AttributeError: 'NoneType' object has no attribute 'price_per_share'

**Comment by shner-elmo** [comment]
> thanks that will solve my problem ill test it out when market opens. also another question while i have the library connected to my tz account i cant open my tradezero right to watch charts etc?

Thats a good question. Unfortunately, you can only have one instance of the TZ WebFree platform open at a time,
so if you open a second (whether it's a second tab or a different device) it will disconnect you from the last one, you can test this, but you can't open a second instance.

So if you want to view the charts or place an order you should use the same instance as the tradezero-api is using.

**Comment by shner-elmo** [comment]
This error:
```py
AttributeError: 'NoneType' object has no attribute 'price_per_share'
```
Means that the value returned by the `tz.locate_stock()`method is `None`, try while the market is open (not today:)
